name: CI

on: push

jobs:
    sonar:
        name: Send project to SonarCloud
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  lfs: true

            - run: |
                  git fetch --prune --unshallow

            - name: Sonarscanner for dotnet
              uses: Secbyte/dotnet-sonarscanner@v2.2
              with:
                  buildCommand: dotnet build src/Bones3.sln
                  testCommand: dotnet test src/Bones3.sln
                  projectKey: TheDudeFromCI_Bones3-Rebuilt
                  projectName: Bones3-Rebuilt
                  sonarOrganisation: thedudefromci
                  beginArguments: >
                      /d:sonar.verbose="true"
                      /d:sonar.cs.opencover.reportsPaths='"src/Test/coverage.opencover.xml"'
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
